apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: proxmox
spec:
  type: ExternalName
  externalName: 192.168.0.4
  ports:
  - name: web
    port: 80
    targetPort: 8006
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
  namespace: proxmox
  annotations:
    external-dns.alpha.kubernetes.io/hostname: proxmox.relyq.dev
spec:
  parentRefs:
    - name: gateway-internal
      namespace: traefik
      sectionName: websecure
  hostnames:
    - proxmox.relyq.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: proxmox
          kind: Service
          port: 8006