apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: proxmox
spec:
  ports:
  - name: websecure
    port: 443
    targetPort: 8006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: proxmox
  namespace: proxmox
  labels:
    kubernetes.io/service-name: proxmox
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.4
    conditions:
      ready: true
ports:
  - name: websecure
    port: 8006
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
  namespace: proxmox
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pve.relyq.dev
    external-dns.alpha.kubernetes.io/dns: pihole
spec:
  parentRefs:
    - name: gateway-internal
      namespace: traefik
      sectionName: websecure
  hostnames:
    - pve.relyq.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: proxmox
          kind: Service
          port: 443