apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
  namespace: oauth2-proxy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: auth.relyq.dev
    external-dns.alpha.kubernetes.io/dns: pihole
spec:
  parentRefs:
    - name: gateway-internal
      namespace: traefik-internal
      sectionName: websecure
  hostnames:
    - auth.relyq.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: oauth2-proxy
          kind: Service
          port: 80