apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:44180
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-User
      - X-Auth-Email