apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 24h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.12.x"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: oauth2-proxy
      interval: 12h
  values:
    config:
      existingSecret: oauth2-proxy
      cookieName: oauth2-proxy
      configFile: |
        provider = "keycloak-oidc"
        upstreams = ["static://200"]
        email_domains = ["*"]
        oidc_issuer_url = "https://keycloak.relyq.dev/realms/claire"
        redirect_url = "https://auth.relyq.dev/oauth2/callback"