apiVersion: v1
kind: ConfigMap
metadata:
  name: init-keycloak-sql
  namespace: postgresql
data:
  init.sql: |
    DO $$
    DECLARE
      user_exists BOOLEAN;
      db_exists BOOLEAN;
    BEGIN
      SELECT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '{{ .KeycloakUser }}'
      ) INTO user_exists;

      IF NOT user_exists THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '{{ .KeycloakUser }}', '{{ .KeycloakPassword }}');
      END IF;

      SELECT EXISTS (
        SELECT FROM pg_database WHERE datname = '{{ .KeycloakDB }}'
      ) INTO db_exists;

      IF NOT db_exists THEN
        EXECUTE format('CREATE DATABASE %I OWNER %I', '{{ .KeycloakDB }}', '{{ .KeycloakUser }}');
      END IF;
    END
    $$;
