apiVersion: v1
kind: Namespace
metadata:
  name: test-recovery

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writer-pvc
  namespace: test-recovery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---

apiVersion: v1
kind: Pod
metadata:
  name: writer
  namespace: test-recovery
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true; do
            date >> /data/log.txt;
            sleep 5;
          done
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: writer-pvc
