apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dashboard-external-route
  namespace: traefik-external
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik-external.relyq.dev
    external-dns.alpha.kubernetes.io/dns: pihole
spec:
  hostnames:
    - traefik-external.relyq.dev
  parentRefs:
    - name: gateway-internal
      namespace: traefik-internal
      sectionName: websecure
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: api@internal
          kind: TraefikService
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: oidc