apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: ">=35.4.0 <36.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      enabled: true
      podAnnotations:
        inject-certs: enabled

    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.12.0"

    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        enabled: true # needed for middlewares

    gatewayClass:
      enabled: true
      name: traefik-external

    ingressClass:
      enabled: false
    gateway:
      enabled: false

    ports:
      web:
        port: 8000
        exposedPort: 9080
        protocol: TCP
        expose:
          default: true
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.1/24
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        exposedPort: 9443
        protocol: TCP
        expose:
          default: true
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.1/24
        tls:
          enabled: true
      netbird-relay:
        port: 33080
        expose:
          default: true
        exposedPort: 33080
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.1/24
        protocol: TCP
        tls:
          enabled: true
      netbird-signal:
        port: 10000
        expose:
          default: true
        exposedPort: 10000
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.1/24
        protocol: TCP
        tls:
          enabled: true