apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  interval: 24h
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: ">=2.30.0 <2.32.0"
      sourceRef:
        kind: HelmRepository
        name: pi-hole
        namespace: pi-hole
      interval: 12h
  values:
    persistentVolumeClaim:
      enabled: false
    admin:
      existingSecret: pi-hole
      passwordKey: admin-password

    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Cluster

    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"