apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: namespaces
    - name: secrets
    - name: snapshot-controller
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/backups/velero
  prune: true
  wait: true
---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: namespaces
    - name: snapshot-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/storage/longhorn
  prune: true
  wait: true