apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: external-dns
  values:
    logLevel: debug

    sources:
      - gateway-httproute

    provider: cloudflare

    cloudflare:
      secretName: cloudflare-api-token
      apiToken: urn:k8s:secret:cloudflare:api-token
      email: relyqx@gmail.com

    annotationFilter: "external-dns.alpha.kubernetes.io/dns=cloudflare"