apiVersion: v1
kind: ConfigMap
metadata:
  name: html-staging
data:
  index.html: |
    <html>
      <head><title>my k3s page</title></head>
      <body><h1>hello from k3s!</h1><p>this is staging</p></body>
    </html>