apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
  ref:
    semver: ">=8.8.5 <8.9.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: external-dns
  values:
    sources:
      - gateway-httproute
      - crd

    provider: cloudflare

    cloudflare:
      apiToken: urn:k8s:secret:cloudflare:api-token
      email: urn:k8s:secret:cloudflare:email

    crd:
      create: true

    annotationFilter: "external-dns.alpha.kubernetes.io/dns=cloudflare"