apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: namespaces
    - name: secrets
    - name: clusterissuers
    - name: postgres
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterissuers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/networking/cert-manager/cluster-issuers
  prune: true
  wait: true