apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: namespaces
    - name: secrets
    - name: postgres
    - name: keycloak-init
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  wait: true
---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-init
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: namespaces
    - name: secrets
    - name: postgres
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/auth/keycloak/init
  prune: true
  wait: true
---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: namespaces
    - name: secrets
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/storage/postgresql
  prune: true
  wait: true
---