apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 24h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.9.x
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
