apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: longhorn
data:
  values.yaml: |
    defaultSettings:
        defaultReplicaCount: 1
        defaultLonghornStaticStorageClass: longhorn-custom

    defaultBackupStore:
      backupTarget: s3://efdi-infra@eu-central-1/relyq/longhorn
      backupTargetCredentialSecret: longhorn-aws-credentials