apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: longhorn
data:
  values.yaml: |
    defaultSettings:
        defaultReplicaCount: 1
        defaultDataPath: /mnt/data/claire/longhorn