apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dashboard-route
  namespace: traefik
spec:
  hostnames:
    - traefik.relyq.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: api@internal
          kind: TraefikService
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure