apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: ">=35.4.0 <36.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    logs:
      general:
        level: INFO

    deployment:
      enabled: true
      podAnnotations:
        inject-certs: enabled

    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.12.0"

    providers:
      kubernetesGateway:
        enabled: true

    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      netbird-relay:
        port: 33080
        expose:
          default: true
        exposedPort: 33080
        protocol: TCP
        tls:
          enabled: true
      netbird-signal:
        port: 10000
        expose:
          default: true
        exposedPort: 10000
        protocol: TCP
        tls:
          enabled: true

    additionalArguments:
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"