apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
  namespace: traefik-ingress
data:
  traefik-values.yaml: |
    deployment:
      enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true

    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true

    additionalArguments:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.kubernetesingress.namespaces=traefik-ingress,nginx"