apiVersion: v1
kind: Namespace
metadata:
  name: traefik-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-ingress
  namespace: traefik-ingress
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-ingress
  namespace: traefik-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: ">=21.0.0 <22.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-ingress
        namespace: traefik-ingress
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: traefik-values.yaml
