apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: traefik
data:
  values.yaml: |
    deployment:
      enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true

    providers:
      kubernetesGateway:
        enabled: true

    ports:
      web:
        port: 80
        exposedPort: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 443
        exposedPort: 443
        tls:
          enabled: true

    additionalArguments:
      - "--entryPoints.web.address=:80/tcp"
      - "--entryPoints.websecure.address=:443/tcp"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.kubernetesingress.namespaces=traefik,nginx"