apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: traefik
data:
  values.yaml: |
    deployment:
      enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true

    providers:
      kubernetesGateway:
        enabled: true

    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true

    additionalArguments:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.kubernetesingress.namespaces=traefik,nginx"