apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: traefik
data:
  values.yaml: |
    deployment:
      enabled: true

    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        allowCrossNamespace: true

    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true

    additionalArguments:
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"