apiVersion: ENC[AES256_GCM,data:SDU=,iv:Frt18PdaAuq/5SiYSNKXg7SIqVFW5dI+y5Nex9DxW88=,tag:MEOOJUkxBrFWtY5qiBRLrg==,type:str]
kind: ENC[AES256_GCM,data:r/d4VwCa,iv:4x5d7AsfGtNLvjYWCmSfz9ySXySTvgXSplYMCZ8cNcI=,tag:uwkcEYHOvRk0KThZq57hQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YKEZgcl+oIe/ja7dyA==,iv:dy/YOYsJ1tsPB7j+Liw0up+GxI0pjXjR1UH+3zfXZ2E=,tag:GSaTPHFYZWk91x9+bCw0OQ==,type:str]
    namespace: ENC[AES256_GCM,data:sstF53niNA==,iv:Me0E2baCk5kNCaENoySFsCjJckvI9S+RJiu8RmQVQAU=,tag:L1NH/Gr6L+sS9iwvmc14Ow==,type:str]
type: ENC[AES256_GCM,data:y19ftlkO,iv:jUfNaybIdBHawHDpEfYFOsWm2Fr11U/hM9donVhgjAo=,tag:rZcvc0uAJWBU3wxJsbKeoA==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:bChCqazJKQ==,iv:DlWBCnvTE1v2Jl3UsD0rU8oZM9lj1jQsx+u59aRZ5g0=,tag:JeUIgn07W44aEFUztCMBnw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:nahf/lCvFDn/rsmrNjsF+ce4rzyaiTRgc6Y6pGE7EGU=,iv:v4nKcmQi7FJbocW3Bqm6TZ/qf50gvzXfNH+wmuBDFxw=,tag:Ff7y4JMQiUZtog2nvCbakw==,type:str]
sops:
    age:
        - recipient: age1ydduc5qtujej24y8clev076eu7jkq8nulnwzhnnlexvm6ecpyvgqmuapwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWGkrdkpkK1VONlBHTWsv
            eENRMVQrVjZVclpQdWk4elViWkZEY2Y2MlhzCjFsS00wMmJiejFMY2YzMEdjK0Rz
            eGl1Vmt0VVBqcGpiZ0FvdzFSZE1YeVUKLS0tIHRMc2lWUXdvcXhxN1QrV1J2aWJq
            SUt6bTJSNmxwQ3VQeUFpV2k1emFkMFEKR45CqJk34LBsfbqJyGRdsOggpfKmODcs
            8Ez8qvWDe3tlRhAQ8igMMncV51HyQKfVA3gL4jmOm+agMVGj4Q9/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T07:05:38Z"
    mac: ENC[AES256_GCM,data:40NeIoOevUDtQtph5MznxIC9m2BLUZc/JB9aEgYcQ0ujDannnvOKD320m2udPGfyz1ytXREIB8G+qSnBPJtluWNNijvZ+fCE2u+2ee/rapJO2xHArmV5gwM4KG7/RvSvrV5s6zgTrJwxt+POy3deQmUFcLVuhGkzo6Gi64TOjFI=,iv:fn3J2+LfW/nNjkWPVdtpJR/7MerQUIsLDNI8IqYKmP0=,tag:/Lw3cr5UuR/ujW0H6A1kYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
