apiVersion: ENC[AES256_GCM,data:rc4=,iv:S+gdNZVkqeqUD4kJ80+075O97gnG+kZUiUhj7c81R4k=,tag:5yTucorlFrhyuOUpJmB/wg==,type:str]
kind: ENC[AES256_GCM,data:/QuXMy1x,iv:kMMSxZeeVUy+CzJggNbeZ7r5TWsEi5HFtjhf7FkyGJk=,tag:YYMpbDOXoym1Ec39ACaTtA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZBIxb/C2cXs=,iv:AIwXHE+TqzvF20p+oEFJhdMTxh36MAccsK+oXIYLBmk=,tag:3gxNGABggWQeTkQmUydcHw==,type:str]
    namespace: ENC[AES256_GCM,data:+GVaOLHNp7A=,iv:jvgjxnlvZBkH9SHBJIBe7FJdkRu4fj7fydo3CGBdpfE=,tag:ePcfLTd31bkX+JzTGKrQwQ==,type:str]
type: ENC[AES256_GCM,data:p+kTJTMX,iv:u+z0ue5YgSx2uINKV97IDnaPZLJorB6dZAY1hfRFcl0=,tag:W35iLWUhEAwDrvN0FKoWUw==,type:str]
stringData:
    keycloak-admin-password: ENC[AES256_GCM,data:gEcGlR0Q0pCe1jxEL/yiL/N6yRc=,iv:qZVt8pSV9/4XANR3UJPEAwRy/edST8eb7qI/jZvpnfU=,tag:p3Bn5vQuA7s6DSHRT0GBnQ==,type:str]
    keycloak-postgresql-host: ENC[AES256_GCM,data:WYvIZKW/aUZ7edxyrA1QsWx97RfmIxJH4rORbcEzyDoxwwksjJJw,iv:5y7E1tdHNGQmza4RJTaQ43K+1W4GKnMrfrPFSx4stUc=,tag:KKOfjdJbaXTCTciUQpa23A==,type:str]
    keycloak-postgresql-port: ENC[AES256_GCM,data:tFEEBQ==,iv:zQWuRnv9Y/z6N4x0dgcKGIPupLW+YlYvvFqjo6s+K4g=,tag:4mH0SYuFlor4QjFUH5roZA==,type:str]
    keycloak-postgresql-database: ENC[AES256_GCM,data:H9UswgzTml8=,iv:4m9K+hVEPhmr1lE3BBSKksZQGnRZmhrpWOQrjwHkwRo=,tag:esXwxxFLZk4TXOu2bpv2GA==,type:str]
    keycloak-postgresql-user: ENC[AES256_GCM,data:Zlo8yrU/qWE=,iv:c20CkKWe7RzitDvhPy6lK9Z0QEYj4airkrDfAGHHeLA=,tag:kEiqfWb0pDm56TryQPfUug==,type:str]
    keycloak-postgresql-password: ENC[AES256_GCM,data:3LoRG2tG9/IciIvizyxRiuYI0lA=,iv:6axYXQk4LfHk/znb2qof8ygpCaPStshw36cHuE+GFY0=,tag:G0fnm6Jj/pw3MUApxz76rw==,type:str]
sops:
    age:
        - recipient: age1ydduc5qtujej24y8clev076eu7jkq8nulnwzhnnlexvm6ecpyvgqmuapwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMGl4QWtlMkVjUjR1am05
            R2t2QUtkWUlkVk5nZHJPZGdZK3VtaDliendFClc2RzdmQzRRSTZBaEVVYnNrTG5Y
            T1VDQWFqRFdkYWFCa0FYVndaWFdxN0EKLS0tIHVHS2F4VitCdzI1NnoxbTd4MWRn
            TE1XMU14czNFT2cwL1VGT2IzZUxrVDgKYRd0mLbuLCXeVTE+u+8Gk55rb8gu6OvB
            6NXa9QKQXkUTap1kkQSsuuIzcCvGLz9IWQOtnM3NpMrjMvmW8cmfGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T06:29:30Z"
    mac: ENC[AES256_GCM,data:mMSVjsi4ifjzUbBMEyk0LyNabsmDbuBi8hGxycMWujYjN7eFQX7dXsHmvsg2ibSWCaJozZJiZnjB/+vXHaY1t/SZUk/bTnl7Cnib3PcIsqYHDcjdyyPdpPltShXkZQNpCN9bvRIQjpVyZj62jh9Vs2hNqodJX/m1gj4s1SfDFjs=,iv:5UvBvUcS+56uJLl3zA6REN1mmTtH6miKHccmkwsVVlo=,tag:V1JMwKGs5Z9Zd4YzcWo3pg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
