apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-token.yaml
  - postgresql-auth.yaml
  - keycloak.yaml
  - keycloak-initdb.yaml
  - obsidian-livesync.yaml
  - velero.yaml
  - longhorn-aws-credentials.yaml
  - longhorn-oidc.yaml
  - traefik-oidc.yaml
  - lute-oidc.yaml
  - grafana-admin.yaml
  - grafana-oauth.yaml