apiVersion: ENC[AES256_GCM,data:lPA=,iv:RCwvEa60qaPQgBqG4Hjvtm6XDviqTEWaQvQf0X+5UhY=,tag:kNQnt9hx7xEu7UN0dleD0A==,type:str]
kind: ENC[AES256_GCM,data:IKZFuntg,iv:rgi+QzF4rX8FzJRwWhvBH8q1il7/bVR7QYrXMuyjplA=,tag:pvEC7DfYWzvrcb1+QntW0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bVtmYw==,iv:pf8eq92DdPV2Ks7xOTaGovQvJGO6GECqhj0EVO6Ll3U=,tag:9Z6QfaYyqYq3ho7cdtToHw==,type:str]
    namespace: ENC[AES256_GCM,data:KHUTuRw9M3U=,iv:av5gSIVpaUEcqGoMhIB4B6ydj4SbU6zt+CR2LTYJtbY=,tag:OpRihzdzfcwASaZDHTSalQ==,type:str]
type: ENC[AES256_GCM,data:RqaEAfxt,iv:cojL4bK036IBiw9MtsABJXSDIdIyH3Db3MDniA+9pFA=,tag:6CeVy587NVzcfq4JNbMXwQ==,type:str]
stringData:
    secret: ENC[AES256_GCM,data:BfT0vYgmDayx6cIb/lQe/fBZafNtd9owlyOchkFby6g=,iv:MxqDR7KYKr4QyEb+uz3uau4zsMvLW0mk221wSmviYb8=,tag:XtjHYRhh2YFaCXDMWi0Hiw==,type:str]
    keycloak-client-id: ENC[AES256_GCM,data:svRWEEp1E1g=,iv:sRXRmA4CpODlXxMWfB3E0n6pr2S3OUsnCHHGoFxctBE=,tag:NItrQztRoHLMqnOYVVSiiA==,type:str]
    keycloak-client-secret: ENC[AES256_GCM,data:ALKI5qkT+VfSDw0HRs3AR7VWoMSvYds1qhW9CnzCRSk=,iv:TuNkSeGlm1QwJ6VOip0ach17O2uQggtUFGWdAf9wCTE=,tag:MGgCrKFxoU4srBdNGMNmAw==,type:str]
sops:
    age:
        - recipient: age1ydduc5qtujej24y8clev076eu7jkq8nulnwzhnnlexvm6ecpyvgqmuapwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU1lySGFsVDdQbnBNZUha
            SDQ5bFN2ZWZWL2dvNmlYMk9EQVN6dUxxRWpBCkJsaml4MFhWdGhrM2NSNTlQcjRk
            cUhPbHV6cnFWK1pCb00zaDA1c2QrcGcKLS0tIDRMSXE4Y0NKTEVlTXYxZWl5U0tD
            ZmhxeWVjSTlwZ1paYmVxVmpxUE9OME0Ke/pDNxFshGNaZfMLc674D3DFE+Np0qWq
            trDSnt3Ru7O4uy/fDioQ0T7+mmCMK41+M+QKDXl4MBC+f1HSiAI7Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T06:06:17Z"
    mac: ENC[AES256_GCM,data:KfAYBUTDNYqEXoCBFjanupAbQfvR2ZSxU/Guc5krpuqHUUdO1+QjwYgiLSVuHickt5eyUiTgftZX6Sut+S7lp9q1yipMw+gzMC1IlN80JXa9ldiN9mt6R7aAZYIHWkujNanV8z7spXXUWD8x9rBBwUUZTSFT2dhRwbghjhwL2mQ=,iv:hCHReq2kpdZ90Bz5XPo5e2DqQ0Kxa8nHTW+ZNZePSXI=,tag:/0ryEmk26JriKtVqkBvGfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
