apiVersion: ENC[AES256_GCM,data:P4A=,iv:E4aqACG6FDu0KwQiBF6uILCP4/nQYgewBo23FtGh+xY=,tag:zLjD8QXn4bo9iKIVyzOCPQ==,type:str]
kind: ENC[AES256_GCM,data:9fp/+VJY,iv:cdh2jBwYJlEjStRAaKuag6XvDZesCkW2ZxxDFTLnxOs=,tag:BPNu2nk8YRdGJq1JNu53Og==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HJFbSEsRCp7NAAOZ,iv:4yOcth9trbmcxCsZ0hi9iVVLPLXtvSl2QU0cMaJss0M=,tag:45qEKZOcIwpamCKK+8S/gg==,type:str]
    namespace: ENC[AES256_GCM,data:gO/KxE1P40vkNdZQ,iv:sb3aMm/dFau+puq/HWzAEpAFtIyVODl3DTOCldIjWDw=,tag:Blj2Ddb7a5+GLxuUPZZTVA==,type:str]
type: ENC[AES256_GCM,data:0GKLN7aM,iv:A9xVUEcNCNi7tQQ2L5LE23vt+6D3+HLqW1jyo+SrI7Y=,tag:tzwVJ/O1ftCy1gsSSiqdAw==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:ineD8ljyX7Khoqrs,iv:jWlCGmYIg7BFoFl6l5PuI/GQOeTuNvB0IOQRTV/sii4=,tag:qL6rDthZ+0x8/MDiYrKekw==,type:str]
    clientSecret: ENC[AES256_GCM,data:VNVQ0PWTiahSFn78i91+YtW3yhvflE+O2ypP2IlcT+0=,iv:3Qc9cfNRFUXKSFwcY9HVRZtZFk3CPmXCR2LUr8GmX24=,tag:HbcFpWyJIeE37H+iak1Dtg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:GtZSBYWnHf0wnzy9EL+76CGas8zTaNBEHJiZa3MKQHClKTRN5sJfem2QWXk=,iv:7wU+yzA+P7KE0zaIzuJBCm/mHvIDdOL303Hnz0Mzz1I=,tag:HV2BlGxxadjf2a7X4L4xUg==,type:str]
sops:
    age:
        - recipient: age1ydduc5qtujej24y8clev076eu7jkq8nulnwzhnnlexvm6ecpyvgqmuapwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcVVSc25IM2FoRjJXTFV2
            SXhUeUdpR2xFU3FzNGZoQ2IyU0xaM3lyYm5zCk1scjQ2YTlsODZjczF2YmJCckN0
            N09xL1ZKamhLVnRhelRiR2cyUndPSXMKLS0tIE1QdXJMNExEaTBnYVFBK2NqS2FY
            SVNRck4wcTg1UUd1cUFJZURqZkd4L1kK3p5LMW+pAc8l/43nDaz1XIsP2OsLLMLT
            DEKWa852eY86QSuEuX8Bxysp/XCUhphPzePPLPXJrRnlNNbF5gc2kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T03:43:02Z"
    mac: ENC[AES256_GCM,data:kG7JvNSmd5qB/i6wagJa4pfxLI1Xcj5LG40dauYuq4cfSxZy1h6dyCd28TmF9lRB9Nt7+fv8YbOX2yGYYamFweaSxEuDng0k+P96MaZI1FwOdGTf7mufx3DW1EsjObPOPTNoilthqmomYy7HE63qNo6SFaQqweqy0oMOQ7/NXFM=,iv:1sBXj0UXJN4FLaDSts5Vmez7XiSXUFq2iIGCh5i8WKw=,tag:NA8oMCZNFHG0Ej6+DS1RXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
