apiVersion: ENC[AES256_GCM,data:krQ=,iv:M58F2sh2lve8SFVZexJ8q1kuNUGKCV1spNSW6x23o80=,tag:5LMVhR2n67u4GR23/+lxeg==,type:str]
kind: ENC[AES256_GCM,data:mMfPiwV4,iv:8hE50kcnyZ8sTqYMhFbW1InKdBiKgxiGVAq0h+anfwY=,tag:0y9zSrqH3rqqTEdrJEAcMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bPIdxKEjfDPyW6g=,iv:0UR7PZVSHsRNyXwbaxXQzSM5L9l8bU7gBKMcG9jT73k=,tag:AUeVKDqnwJXRW8jXTDdqWw==,type:str]
type: ENC[AES256_GCM,data:tK2df3j4,iv:TbQw07zpiexyAaRUU59x/Z+0VWzrv6TKGmG3t/lCgDI=,tag:ki454j6r28ajL/EWNq1tuQ==,type:str]
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:G/JehSE=,iv:ltFSjsi+VUSyw7mrX2lW86RcZ+MWf6wvfmdt/3kXums=,tag:d5ZP1vCGpuyAamy4oB7hAw==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:A+PUJrt+nKfnd0ZOCIu5mha/bF4=,iv:Z6IGFOqgS37y04tdOL+xpWqoLaTgggWeXZirfwLfy1g=,tag:DNJbiYpe7onmAkpbRNqneA==,type:str]
sops:
    age:
        - recipient: age1ydduc5qtujej24y8clev076eu7jkq8nulnwzhnnlexvm6ecpyvgqmuapwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NnpaQno0V1VtM3RnOCtu
            ZW1LMHllSlZkOE5KV1VLaGxBL2p6U0tNZ20wCnJibGpLRG5vcTl5ckhKbEoyMEt2
            UFVtanhBNFVvNnl5OEU5YU9pNnVsZTgKLS0tIGl0TVh3bVBXeGVadkp4RmxCcU5x
            OXJCc2drcUhPVTUyTyt5WXp1M2FEV2cKaZJFfbdOj/PYpnvo8l9nBWuM+OZOeEXO
            xwCDeKUg4BDbYpXirafowUNB88udfecf1vItHo3YQZifticgatVcBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T06:18:15Z"
    mac: ENC[AES256_GCM,data:TvHW6C5irG4Zic02tavJZCW75rdvrcgdg5VYVdwbPKIrUq+GZYmKpdCRfAlVusau8vMGhxLQ/seQVZufCp7bOL72Qk/yQ6id14UyjuL3gIOgE7nL/IbI9dG4RSB7B2t+955Jbc+5oKqlqG3AdaF/bTRbIVesvyvZ8lh46Sl8VOo=,iv:gAyiXPfyopUsbGcQlQCZATjyYr2FMvE5D9zs5lLCOu8=,tag:rOGSaWoDdRqs+4ZUwbZPNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
