apiVersion: ENC[AES256_GCM,data:MPs=,iv:pS3JPj6Cy5bDpryJ4OIT0+5PvHKwwzX2RcgGjMrhxq8=,tag:Ug7jdyOQe9bfY1gaY8e7TA==,type:str]
kind: ENC[AES256_GCM,data:YJDzrI45,iv:SFWbRw4vsRmRmWcAoQfFjnsI9DYca8UpPcHq4q6Q3k4=,tag:Y3WjQR5FSreryXv6EvPyUQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wvnnCYoVPv8pOXFab3Dv,iv:dwZtMJPNmjnSX017O95gES6yGczrEpLSXKkgRdrrnvs=,tag:PXNDjmdLquKdnvidvMKJmw==,type:str]
    namespace: ENC[AES256_GCM,data:gws1+7Vr5XURHQ==,iv:aigf7/RFfTDDT8jxU1qbF4egI9eMpFwoQ13HgfyyG0Q=,tag:O4X0CJyTIv90XCjw+tFLKw==,type:str]
type: ENC[AES256_GCM,data:FuHgzLwF,iv:f7YQ3swWCwp6l/y87SJv/bnD8JXul99C8fyq616Xd8g=,tag:nT2kHycI/+1lmFnBLe0eQA==,type:str]
stringData:
    postgresql-admin-password: ENC[AES256_GCM,data:T1HWHkGeCQuk4B8vFoK2D0FBAl0=,iv:4qOjC9fEvEMfiFrdius19UsWbxB2I1xqD77Wmq8expw=,tag:DITy/sLcGDzt4Xi6LC+CRw==,type:str]
    postgresql-user-password: ENC[AES256_GCM,data:giwisf0Iz0h9+wIO+xt4NDdjxsY=,iv:hnp9CQ+udJviixrjBbxpBuTWAlUz6nUOTazxnwwIXoU=,tag:3uv4ddmC1ZZ6xe5jGZ1JaA==,type:str]
sops:
    age:
        - recipient: age1ydduc5qtujej24y8clev076eu7jkq8nulnwzhnnlexvm6ecpyvgqmuapwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaEpJYkFtNURuYk9lOW80
            UEZQWElPYlhueUt5cnpXaTRteUhuRFk5VUNvClRnNit0bVNOODVSNmpuR3JoQnlt
            V0dqNnN0dWJRM25IL1ZXMVkyL2lNeTgKLS0tIEZ4eVNjOXVSU0ZETGV6RzVEWU5j
            N3VUZXBuOGZoVEJ0RTY2QWpOTXNWUE0KQF7AV2Dr4jLdLSnHPnqdu1uNVEgd1KHc
            2hlTCduhEBwq46MTGfBI7O/I8vkXMw8LHTeJ5UDh88EQL/1d7ppgTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T17:46:58Z"
    mac: ENC[AES256_GCM,data:0UuZNDyxVqIF5t63whDs65SMWC/GXUDqsNEsYG+EhAvINTcsV05fM1mtOtsTsXgD7A9KIs9D5ldVUtrOzhNU4D5R+wY1SPn2YC4CiTEB3fv6JzAStMH9P36iDqAU9vragDo+KrEVXJfWI4C+Oryp0OT5el1Np/HMjd8vHxTeu9k=,iv:J6OAchnDp4sbWaWoHOxMDA+Rk6/PcGULH2hT8aBwvz8=,tag:9LborFhMt3D8gzYbxMXfSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
