apiVersion: ENC[AES256_GCM,data:Yw0=,iv:ERfG1n/KhKC68LZiplxNv1L42X1dwT/Evs9PLfgnCvw=,tag:oAN7/kVkFekaNSiKsczqKA==,type:str]
kind: ENC[AES256_GCM,data:hmXgOvI/,iv:WaeDN8OlFtITGe0crVeSbUqYIdF/B80OMiJRXVsCtJE=,tag:1VgB+Aj/JsG8RHYRO8iXcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0eAdG4gw,iv:NrZTW/lZ6SIWqMkHhb3JbVNZhUm5dEvuowiAakK+iyg=,tag:iANymmQU9qIIyWfI9zqG3A==,type:str]
    namespace: ENC[AES256_GCM,data:67CTa/xY,iv:PW1EiOT7bJdXB8SCS7+MmaoERNY4T12d/ZiFNS+Sg8Y=,tag:U62ivIGwZ5kjGhf9URFAzA==,type:str]
type: ENC[AES256_GCM,data:NErNyApq,iv:y4hYwHnxV49N/pOrshkHm/7EGIX9AA5p2PtCQYywVYQ=,tag:vgXKZFwJE3J95FIo2gsEnQ==,type:str]
stringData:
    aws-efdi: ENC[AES256_GCM,data:K1bZaN3Ir+wn4sXaA7U7oRKU90henRzvfs34NlzbLdB9o04bAh0SL7NIKTjzeHzN6Hs3ATUldWXmwoOJfeLpyK7BuVEH8HL3I8SHJZDMD5TlbRQZXEDS2w7FpI6S4xVesgWnUnbaisaN2WzZ41+30mXMszU=,iv:frBRKGOEybDWDwDQSnnvdqBCSdoHLO9ueslkqH4J6OI=,tag:JeNsVacvy3mqzKvK6nlrLQ==,type:str]
sops:
    age:
        - recipient: age1ydduc5qtujej24y8clev076eu7jkq8nulnwzhnnlexvm6ecpyvgqmuapwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYmkwVm9YVWRlaTZrTHcw
            NWx0aUVBWmpiMFhUZUlxWFd1Y051ZHdVN1g0CkQ4RmJ3SzdIckZmOU5oY2R0L1NJ
            M3phQ2h2SUpzUXcxOXNVSURrdHUyR1kKLS0tIDZwTVZXTkRDQXA1V05CUXNMUWV6
            dXhLQnJLZjY1UUpicFNlek9XQjdiQjgKroB6/7mUNuaPyMzTWNVz7HolQ2UIKQnH
            aczipLVXlneV2LlhXcTdZvENHY5J3+TkcvbB42OnbwOcF2nElqr+NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T04:55:32Z"
    mac: ENC[AES256_GCM,data:IoYQUoBQNXCC5GnGFbce/9C4shRFbVQd6Zp82cpH/jmUDZCJp9oFsGoEYvOi2rgM3AV2WHKFPYiEBKm+4w+nzQ+rr9k3F+4GPhcAqQLFM43rahiQd5E2wt1jocjjWbgUk+j02z6vnoYj0C4R0K4FKSuFFg+cKwQJWKcZ81XhgQY=,iv:7QCbrU8LV54hJv9Bp+biNiUn5t6adAEFVWaMUh6wxiU=,tag:QlBfF0yqch3lSWspQsBMFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
