apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: relyqx@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
    - dns01:
        cloudflare:
          email: relyqx@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault.vault.svc.cluster.local:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkekNDQWwrZ0F3SUJBZ0lVSHJhNGh5dnU2NW9sVjBicm9Ick9yNUU5TzFVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pERWlNQ0FHQTFVRUF4TVpRMnhoYVhKbElGWmhkV3gwSUVsdWRHVnliV1ZrYVdGMFpUQWVGdzB5TlRBMwpNRFF4TWpNNE1UTmFGdzB5TmpBMk1qZ3dNREF3TURCYU1DZ3hKakFrQmdOVkJBTVRIWFpoZFd4MExuWmhkV3gwCkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQXd3WEMwTThIclp6bi93MnhwcVp2alJvekNEZGovT2dvazVOODl5MW04aDZKYTRLZC9aLzlWQ2U4eEVjUAp5WnJQZlcwSnpBYTQwVlVSK0FwNFZCWkhWdXE4aXl5NktFMVlaMkRhNTMxNjJyeDFFUzVjVTZrV3Q2STdIcTRUCjNWcmFXbld2NU9oaXVEMGxBM1hYSlcrbkpQZjFWUk9sSndpYUk0b3pkTndvaER2MWROVVF3RG8zamptUXdWYTgKT3BXcTh6SkQ0ajFZV2hQZHBkRXRBQk1waXYwbU53L095TlJIN2tJR25ieDc0bUcrRG9JaEx0ZmRaS3pTbHRIMApOTVNKTXVXdUlESG9SSUdJWWY1VzJhbEhUZkZxdmxIYnBUc2FNaFNYZVUxZmdzWXR2dmNaRlE5OVJTYTViMXJzCmp2QUttQlNGRzhKcE84M3c3S0Vsb1FLM053SURBUUFCbzRHY01JR1pNQTRHQTFVZER3RUIvd1FFQXdJRHFEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0hRWURWUjBPQkJZRUZDV29YTC92dHU1WAp6eUtCb3ZxSVNuaVhDV0tnTUI4R0ExVWRJd1FZTUJhQUZJUFhhdEZCYXNWR29PVTY2cm91aHcrWElzYWFNQ2dHCkExVWRFUVFoTUIrQ0hYWmhkV3gwTG5aaGRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBejl2TFVFWVQrUzQzMm5wZ0pXMWN5MFJHR0Q0VldVMEN3V3JUejUrb3QveVY1T0tZbwppemVYTHlKenRSV0JwbC9kUkpPV2h1c01JeUtrblp3RDZrQWJFZEdGa3prSlFEam9MVjJTVmlGVkszcTIxa3pOCng1VzF0YzB3Z2pFRExHWW9EaWVVdWpKeHRCdU5QRG02NlZGYUhqNEY0NHVlMEV5NUJhR1JUa1FRL3M0TCttMHgKQmxTYm5CSGpxMTl0bWhqendUM0tMLzcxNVZEaTVqMUY3M3FScWE5WGhNZmhlanFROG5kMzVIR0J4eG53MW5vcQpnZ3JOZ0NQdzBlbm1iQlZJeEt4Q21MUnY2UE1iWWtBbHlsVituREovcWVnR3ZtdlhEanFOQ0RROVppZ25tOGtGCkhlS2Zrcm9TQVNpN0NWOEFwNVZYV3pDSG1QaEI2NFdpVFdvTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    path: pki/sign/main
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: vault-issuer
        serviceAccountRef:
          name: cert-manager
          audiences:
            - vault://cert-manager/cert-manager