apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: cert-manager
data:
  values.yaml: |
    installCRDs: true
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true