apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-internal
  namespace: traefik-internal
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: "*.relyq.dev"
    traefik.kubernetes.io/instance: traefik-internal
spec:
  gatewayClassName: traefik-internal
  listeners:
    - name: web
      protocol: HTTP
      port: 8000
      hostname: "*.relyq.dev"
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure
      protocol: HTTPS
      port: 8443
      hostname: "*.relyq.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-relyq-dev-tls-internal
            kind: Secret
            namespace: traefik-internal
      allowedRoutes:
        namespaces:
          from: All