apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik-internal
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: ">=35.4.0 <36.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-internal
      interval: 12h
  values:
    logs:
      general:
        level: INFO

    deployment:
      enabled: true
      podAnnotations:
        inject-certs: enabled

    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.12.0"

    providers:
      kubernetesGateway:
        enabled: true
        labelselector: "app.kubernetes.io/instance=traefik-internal-traefik-internal"
      kubernetesCRD:
        enabled: true # needed for middlewares

    gatewayClass:
      enabled: true
      name: traefik-internal
    ingressClass:
      enabled: false

    gateway:
      enabled: true
      name: gateway-internal
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: "*.relyq.dev"
      listeners:
        web:
          port: 8000
          protocol: HTTP
          hostname: "*.relyq.dev"
          namespacePolicy: All
        websecure:
          port: 8443
          protocol: HTTPS
          hostname: "*.relyq.dev"
          mode: Terminate
          certificateRefs:
            - name: wildcard-relyq-dev-tls-internal
          namespacePolicy: All

    ports:
      web:
        port: 8000
        exposedPort: 80
        protocol: TCP
        expose:
          default: true
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        exposedPort: 443
        protocol: TCP
        expose:
          default: true
        tls:
          enabled: true