apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
  namespace: keycloak
spec:
  hostnames:
    - keycloak.relyq.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: keycloak
          kind: Service
          port: 80
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure