apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: ">=20.0.0 <21.2.2"
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml