apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: keycloak
data:
  values.yaml: |
    global:
      defaultStorageClass: "longhorn-custom"

    auth:
      adminUser: admin
      existingSecret: keycloak
      passwordSecretKey: keycloak-admin-password

    postgresql:
      enabled: false

    externalDatabase:
      existingSecret: keycloak
      existingSecretHostKey: keycloak-postgresql-host
      existingSecretPortKey: keycloak-postgresql-port
      existingSecretUserKey: keycloak-postgresql-user
      existingSecretDatabaseKey: keycloak-postgresql-database
      existingSecretPasswordKey: keycloak-postgresql-password

    proxy: edge