apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
  ref:
    semver: ">=8.8.5 <8.9.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: external-dns
  values:
    sources:
      - gateway-httproute
    provider: pihole
    pihole:
      server: https://pi-hole-pihole-dns-tcp.pi-hole.svc.cluster.local
      secretName: pi-hole-password