apiVersion: v1
kind: Service
metadata:
  name: relay-service
  namespace: netbird
spec:
  clusterIP: None
  ports:
  - name: http
    port: 33080
    targetPort: 33080
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: relay-service
  namespace: netbird
subsets:
  - addresses:
      - ip: 192.168.0.101
    ports:
      - port: 33080
        name: http
        protocol: TCP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: relay-route
  namespace: netbird
spec:
  hostnames:
    - netbird.relyq.dev
  parentRefs:
    - name: gateway-internal
      namespace: traefik
      sectionName: netbird-relay
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /relay
      backendRefs:
        - name: relay-service
          port: 33080