apiVersion: v1
kind: Service
metadata:
  name: signal-service
  namespace: netbird
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10000
    targetPort: 10000
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: signal-service
  namespace: netbird
subsets:
  - addresses:
      - ip: 192.168.0.101
    ports:
      - port: 10000
        name: grpc
        protocol: TCP

---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: signal-route
  namespace: netbird
spec:
  hostnames:
    - netbird.relyq.dev
  parentRefs:
    - name: gateway-external
      namespace: traefik
      sectionName: netbird-grpc-signal
  rules:
    - matches:
      - method:
          service: signalexchange.SignalExchange
      backendRefs:
        - name: signal-service
          port: 10000