apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: ">=15.0.0 <16.7.10"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: OCIRepository
        name: postgresql
        namespace: postgresql
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
