apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: postgresql
data:
  values.yaml: |
    auth:
      username:
      password:
      database: claire
      existingSecret: postgresql-auth
      secretKeys:
        adminPasswordKey: postgresql-admin-password
        userPasswordKey: postgresql-user-password

    primary:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: "longhorn-custom"
        accessModes:
          - ReadWriteOnce

    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

    volumePermissions:
      enabled: true