apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: ">=0.30.0 <0.31.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
      interval: 12h
  values:
    server:
      enabled: true
      dataStorage:
        enabled: true
        storageClass: longhorn-custom
        size: 4Gi
      annotations:
        inject-certs: enabled
      volumeMounts:
        - name: cluster-cert
          mountPath: /etc/ssl/private
          readOnly: true
      volumes:
        - name: cluster-cert
          secret:
            secretName: cluster-cert-secret

      standalone:
        enabled: true
        config: |-
          ui = true

          listener "tcp" {
            tls_disable = 0
            tls_cert_file = "/etc/ssl/private/tls-cluster.crt"
            tls_key_file = "/etc/ssl/private/tls-cluster.key"
            tls_disable_client_certs = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "file" {
            path = "/vault/data"
          }

    ui:
      enabled: true