apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: ">=0.30.0 <0.31.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
      interval: 12h
  values:
    server:
      enabled: true
      dataStorage:
        enabled: true
        storageClass: longhorn-custom
        size: 4Gi
      annotations:
        inject-certs: enabled

    ui:
      enabled: true
      annotations:
        inject-certs: enabled