apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: ">=0.30.0 <0.31.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
      interval: 12h
  values:
    server:
      enabled: true
      dataStorage:
        enabled: true
        storageClass: longhorn-custom
        size: 4Gi
      annotations:
        inject-certs: enabled
      volumeMounts:
        - name: cluster-cert
          mountPath: /vault/userconfig
          readOnly: true
      volumes:
        - name: cluster-cert
          secret:
            secretName: cluster-cert-secret
      readinessProbe:
        path: /v1/sys/health?standbyok=true
        port: 8203

      standalone:
        enabled: true
        config: |-
          ui = true

          listener "tcp" {
            tls_disable = 0
            tls_cert_file = "/vault/userconfig/tls-cluster.crt"
            tls_key_file = "/vault/userconfig/tls-cluster.key"
            tls_disable_client_certs = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          listener "tcp" {
            address = "[::]:8203"
            tls_disable = 1
          }

          storage "file" {
            path = "/vault/data"
          }

    ui:
      enabled: true
      externalPort: 8203
      targetPort: 8203