apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb
  namespace: obsidian-livesync
spec:
  interval: 24h
  url: https://apache.github.io/couchdb-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: couchdb
  namespace: obsidian-livesync
spec:
  interval: 30m
  chart:
    spec:
      chart: couchdb
      version: "4.6.x"
      sourceRef:
        kind: HelmRepository
        name: couchdb
        namespace: obsidian-livesync
      interval: 12h
  values:
    clusterSize: 1

    createAdminSecret: false
    extraSecretName: couchdb-env

    persistentVolume:
      enabled: true
      storageClass: longhorn-custom
      size: 4Gi
      accessModes:
        - ReadWriteOnce

    couchdbConfig:
      couchdb:
        uuid: 772ec1d5-d268-4bb6-8366-f6693b07ac6b
      chttpd:
        enable_cors: true
        require_valid_user: true
        max_http_request_size: 4294967296
        max_document_size: 50000000
      chttpd_auth:
        require_valid_user: true
      httpd:
        enable_cors: true
        WWW-Authenticate: 'Basic realm="couchdb"'
      cors:
        origins: 'app://obsidian.md,capacitor://localhost,http://localhost,https://obsidian-livesync.relyq.dev'
        credentials: true