apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb
  namespace: obsidian-livesync
spec:
  interval: 24h
  url: https://apache.github.io/couchdb-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: couchdb
  namespace: obsidian-livesync
spec:
  interval: 30m
  chart:
    spec:
      chart: couchdb
      version: ">=4.5.7 <4.6.1"
      sourceRef:
        kind: HelmRepository
        name: couchdb
        namespace: obsidian-livesync
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
