apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb
  namespace: obsidian-livesync
spec:
  interval: 24h
  url: https://apache.github.io/couchdb-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: couchdb
  namespace: obsidian-livesync
spec:
  interval: 30m
  chart:
    spec:
      chart: couchdb
      version: "4.6.x"
      sourceRef:
        kind: HelmRepository
        name: couchdb
        namespace: obsidian-livesync
      interval: 12h
  values:
    clusterSize: 1

    createAdminSecret: false
    extraSecretName: couchdb-env

    persistentVolume:
      enabled: true
      storageClass: longhorn-custom
      size: 4Gi
      accessModes:
        - ReadWriteOnce

    couchdbConfig:
      couchdb:
        uuid: 772ec1d5-d268-4bb6-8366-f6693b07ac6b