apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: couchdb-route
  namespace: obsidian-livesync
  annotations:
    external-dns.alpha.kubernetes.io/hostname: obsidian-livesync.relyq.dev
    external-dns.alpha.kubernetes.io/dns: pihole
spec:
  hostnames:
    - obsidian-livesync.relyq.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: couchdb-svc-couchdb
          kind: Service
          port: 5984
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: obsidiancors
  parentRefs:
    - name: gateway-internal
      namespace: traefik
      sectionName: websecure
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: obsidiancors
  namespace: obsidian-livesync
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - PUT
      - POST
      - HEAD
      - DELETE
    accessControlAllowHeaders:
      - accept
      - authorization
      - content-type
      - origin
      - referer
    accessControlAllowOriginList:
      - app://obsidian.md
      - capacitor://localhost
      - http://localhost
      - https://obsidian-livesync.relyq.dev
    accessControlAllowCredentials: true
    accessControlMaxAge: 3600
    addVaryHeader: true