apiVersion: v1
kind: Namespace
metadata:
  name: obsidian-livesync
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian-livesync
resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml