apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: obsidian-livesync
data:
  values.yaml: |
    clusterSize: 1

    createAdminSecret: false
    extraSecretName: obsidian-livesync

    persistentVolume:
      enabled: true
      storageClass: longhorn-custom
      size: 4Gi
      accessModes:
        - ReadWriteOnce
      existingClaims:
        - volumeName: obsidian-livesync-couchdb-pvc
          claimName: obsidian-livesync-couchdb-pvc
          persistentVolumeName: obsidian-livesync-couchdb-pvc
          volumeSource: obsidian-livesync-couchdb-pvc

    couchdbConfig:
      couchdb:
        uuid: 772ec1d5-d268-4bb6-8366-f6693b07ac6b