apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-pihole
  namespace: external-dns
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: external-dns
  values:
    sources:
      - gateway-httproute
      - crd

    provider: pihole

    pihole:
      server: http://pi-hole-pihole-web.pi-hole.svc.cluster.local
      secretName: pi-hole-password
      tlsSkipVerify: true # shouldn't skip tls, but serving initial cert from pi-hole requires extra setup

    extraEnvVars:
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: "6"

    crd:
      create: true

    annotationFilter: "external-dns.alpha.kubernetes.io/dns=pihole"