apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: velero
  namespace: velero
spec:
  interval: 24h
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      version: 10.0.x # auto-update to semver bugfixes only
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: velero
  interval: 15m
  timeout: 5m
  releaseName: velero
  values:
    initContainers:
       - name: velero-plugin-for-aws
         image: velero/velero-plugin-for-aws:v1.12.1
         imagePullPolicy: IfNotPresent
         volumeMounts:
           - mountPath: /target
             name: plugins

    credentials:
      existingSecret: velero

    backupsEnabled: true
    snapshotsEnabled: true

    configuration:
      features: EnableCSI
      defaultVolumeSnapshotLocation: csi:longhorn

      backupStorageLocation:
      - name: aws-efdi
        provider: aws
        bucket: efdi-infra
        prefix: relyq/velero
        default: true
        accessMode: ReadWrite
        credential:
          name: velero
          key: cloud
        config:
          region: eu-central-1
          s3Url: https://s3.eu-central-1.amazonaws.com

      volumeSnapshotLocation:
      - name: longhorn
        provider: csi
        config:
          region: default

    schedules:
      weekly-backup:
        disabled: false
        schedule: "0 0 * * 0"
        useOwnerReferenceInBackup: false
        excludedNamespaceScopedResources:
          - certificates.cert-manager.io
          - certificaterequests.cert-manager.io
          - challenges.cert-manager.io
          - orders.cert-manager.io
        template:
          ttl: 730h
          snapshotVolumes: true
          storageLocation: aws-efdi
          volumeSnapshotLocations:
            - longhorn