apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: ">=9.2.8 <9.3.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 12h
  values:
    persistence:
      enabled: true
      type: pvc
      size: 4Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-custom
    route:
      main:
        enabled: true
        hostnames:
          - grafana.relyq.dev
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
            sectionName: websecure
        matches:
          - path:
              type: PathPrefix
              value: /
    admin:
      existingSecret: grafana-admin
      userKey: admin-username
      passwordKey: admin-password

    envFromSecret: grafana-oauth

    grafana.ini:
      auth:
        generic_oauth:
          enabled: true
          name: Keycloak-OAuth
          client_id: env_var_override
          client_secret: env_var_override
          scopes: openid email profile offline_access roles
          email_attribute_path: email
          login_attribute_path: username
          name_attribute_path: full_name
          auth_url: https://keycloak.relyq.dev/realms/claire/protocol/openid-connect/auth
          token_url: https://keycloak.relyq.dev/realms/claire/protocol/openid-connect/token
          api_url: https://keycloak.relyq.dev/realms/claire/protocol/openid-connect/userinfo
          role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'