apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: ">=9.2.8 <9.3.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 12h
  values:
    persistence:
      enabled: true
      type: pvc
      size: 4Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-custom
    route:
      main:
        enabled: true
        hostnames:
          - grafana.relyq.dev
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
            sectionName: websecure
        matches:
          - path:
              type: PathPrefix
              value: /
    admin:
      existingSecret: grafana
      userKey: admin-username
      passwordKey: admin-password