apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lute-data
  namespace: lute-gos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-custom
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lute-backups
  namespace: lute-gos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-custom